[package]
name = "knitchart"
version = "0.1.0"
authors = ["gmadrid"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.0"
graphics_buffer = "0.7.2"
piston2d-graphics = "0.35.0"
